# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/LED_PR/LED_PR.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR || ORIG_REF_NAME==LED_PR} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_microblaze_0_0/LED_PR_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_microblaze_0_0 || ORIG_REF_NAME==LED_PR_microblaze_0_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_dlmb_v10_0/LED_PR_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_dlmb_v10_0 || ORIG_REF_NAME==LED_PR_dlmb_v10_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_ilmb_v10_0/LED_PR_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_ilmb_v10_0 || ORIG_REF_NAME==LED_PR_ilmb_v10_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_dlmb_bram_if_cntlr_0/LED_PR_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==LED_PR_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_ilmb_bram_if_cntlr_0/LED_PR_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==LED_PR_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_lmb_bram_0/LED_PR_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_lmb_bram_0 || ORIG_REF_NAME==LED_PR_lmb_bram_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_xbar_0/LED_PR_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_xbar_0 || ORIG_REF_NAME==LED_PR_xbar_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_microblaze_0_axi_periph_0/LED_PR_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_microblaze_0_axi_periph_0 || ORIG_REF_NAME==LED_PR_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_microblaze_0_axi_intc_0/LED_PR_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_microblaze_0_axi_intc_0 || ORIG_REF_NAME==LED_PR_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_microblaze_0_xlconcat_0/LED_PR_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_microblaze_0_xlconcat_0 || ORIG_REF_NAME==LED_PR_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_mdm_1_0/LED_PR_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_mdm_1_0 || ORIG_REF_NAME==LED_PR_mdm_1_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_clk_wiz_1_0/LED_PR_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_clk_wiz_1_0 || ORIG_REF_NAME==LED_PR_clk_wiz_1_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_rst_clk_wiz_1_100M_0/LED_PR_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==LED_PR_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_axi_uartlite_0_0/LED_PR_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_axi_uartlite_0_0 || ORIG_REF_NAME==LED_PR_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_axi_gpio_0_0/LED_PR_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_axi_gpio_0_0 || ORIG_REF_NAME==LED_PR_axi_gpio_0_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_axi_gpio_1_0/LED_PR_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_axi_gpio_1_0 || ORIG_REF_NAME==LED_PR_axi_gpio_1_0} -quiet] -quiet

# IP: bd/LED_PR/ip/LED_PR_Led_SAXI_01_0_0/LED_PR_Led_SAXI_01_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_PR_Led_SAXI_01_0_0 || ORIG_REF_NAME==LED_PR_Led_SAXI_01_0_0} -quiet] -quiet

# XDC: c:/VProject/Attempt_2_09-04-2024/SAXI_MB_PR_01/SAXI_MB_PR_01.gen/sources_1/bd/LED_PR/LED_PR_ooc.xdc
